### ISSUE TITLE
Migrating to the newly installed Joplin Server

### ISSUE THREAD

**Issue by bernd-wechner** [hi-ko/joplin-server-ubuntu-install#5]
We really need to document that too. As I'm stuck. The server now works, I can even surf to it and am presented with a login.  Likewise, if I try and set it up a synchronisation target in Joplin I need an email and password. I've look on-line at length and found no joy. 

Looked into the database and there's a users table with a single admin entry. But it has a password and one would not expect passwords to be saved in clear text but typically in one way encrypted format (i.e. not decryptable, supplied password is encrypted and compared with database record). So I tried creating a new user tuple, which isn't trivial as not all columns are clear in their meaning, even if mostly so, but as suspected using the email and password entered into that tuple and I cannot log in on the web interface.

So whatever people are doing to create a user account to use their beta Joplin server is worth documenting methinks. For now I'm stuck

**Comment by hi-ko** [comment]
@bernd-wechner you may ask / discuss this with @laurent22 in the Joplin Forum. This project here is initiated as a dump how I installed joplin by replaying the docker file. But of course, I welcome your efforts!

**Comment by rokdd** [comment]
Honestly, I guess that it is hard to understand what you mean because you are mentioning multiple problems?

I used another script to install Joplin Server initially and [made my own](https://rokdd.xyz/tech/self-hosted-joplin-server-without-docker-on-raspberry/) before I found the work of hi-ko in this repo. The credentials are default by the developers as mentioned [here](https://github.com/laurent22/joplin/blob/dev/packages/server/README.md):

> Secure the admin user
> 
> By default, the instance will be setup with an admin user with email admin@localhost and password admin and you should change this. To do so, open https://example.com/joplin/login and login as admin. Then go to the Profile section and change the admin password.

In my database the password is hashed, I don't know what you mean that with that:

> Looked into the database and there's a users table with a single admin entry. But it has a password and one would not expect passwords to be saved in clear text but typically in one way encrypted format (i.e. not decryptable, supplied password is encrypted and compared with database record). So I tried creating a new user tuple, which isn't trivial as not all columns are clear in their meaning, even if mostly so, but as suspected using the email and password entered into that tuple and I cannot log in on the web interface.

**Comment by bernd-wechner** [comment]
Fantastic, all I needed to know was:

>  email admin@localhost and password admin 

And I have logged on, changed it, added a new user, and can log in as that new user.

Anyhow it looks like we're both Swiss and not fans of docker ;-).

Anyway, yes looking into the database, the saved password field is indeed an encrypted version of the one I used. As expected, and why I needed the admin login interface to save an encrypted password.

Looks like I'm rolling, have taken a Jex backup of y Joplin data and can now try and switch to synch to my server and see what happens.

**Comment by rokdd** [comment]
Well that's half true, being a German in Switzerland :-) I guess we can close this here.

**Comment by bernd-wechner** [comment]
Yep. My README PR includes the steps shared here. I'm German born, but a Swiss national, living in Tasmania.

**Comment by bernd-wechner** [comment]
And it seems to be working fine. The feedback on the apps is disconcerting. I synched on my desktop by pushing all local data. That was fine. Then on  my phone and it went a said it was creating remote items, hundreds as and all of them (I have over 1000) and so I panicked and stopped it and inspected. Could find no doubles so ventured a continuation and it finished and said it created 1000+ remote items. But in both phone app and desktop app I see no doubles, all looks ordinary.  Seems to me it was just poor feedback, and the phone app wanted to say it was "comparing local with remote and " not creating a remote item.

**Comment by rokdd** [comment]
> .. it went a said it was creating remote items, hundreds as and all of them (I have over 1000) and so I panicked and stopped it and inspected. Could find no doubles so ventured a continuation and it finished and said it created 1000+ remote items. But in both phone app and desktop app I see no doubles, all looks ordinary. Seems to me it was just poor feedback, and the phone app wanted to say it was "comparing local with remote and " not creating a remote item.

Well I had experienced the same..
